
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          path: new-repo
          
      - name: Repos name and New name
        run: |
          echo ${{github.event.repository.name}}
          echo hello-world-javascript-actions - ${{github.run_number}}
