
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          path: hello-world-javascript-actions
          destination-repository-name: "hellow-world-javascript-actions - ${{github.run_number}}" 
          
      - name: Re-name the repo
        run: |
          echo hello-world-javascript-actions - ${{github.run_number}}
