
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          path: code-for-fun-alums/new-repo-${{github.run_number}}
          
      - name: Repos name and New name
        run: |
          echo ${{github.event.repository.name}}
          echo hello-world-javascript-actions - ${{github.run_number}}
